apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-rs
  labels:
    app: wordpress-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress-deployment
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress-deployment
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-wp
        - name: WORDPRESS_DB_PASSWORD
          value: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pvc
