apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress-deployment
  name: wordpress-service
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress-deployment
  sessionAffinity: None
  type: LoadBalancer
